'use client'

import { useState } from 'react'
import { Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, FileCheck2, Flame, Grid2X2, Menu, MoreHorizontal, Play, Plus, Search, Settings, Sparkles, WalletCards, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const courses = [
  { title:'AI & Automation', description:'Build smarter workflows with practical AI.', cohort:'Nov 2026 cohort', progress:72, week:'Week 5 of 8', modules:'12 of 16 modules complete', color:'ai', tag:'purple' },
  { title:'Python Programming', description:'Think in code. Create with confidence.', cohort:'Oct 2026 cohort', progress:44, week:'Week 3 of 8', modules:'7 of 16 modules complete', color:'python', tag:'blue' },
]

function Stat({ label, value, suffix, detail, icon, tone, bar }: {label:string;value:string;suffix?:string;detail:string;icon:React.ReactNode;tone:string;bar?:number}) {
  return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon ${tone}`}>{icon}</span></div><div className="stat-number">{value}{suffix && <span>{suffix}</span>}</div>{bar !== undefined && <div className="progress-line"><i style={{width:`${bar}%`}} /></div>}<small className={detail.startsWith('↑') ? 'success' : ''}>{detail}</small></div>
}

export default function Dashboard() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [toast, setToast] = useState('')
  const notify = (message:string) => { setToast(message); window.setTimeout(() => setToast(''), 2200) }
  const nav: { icon: LucideIcon; label: string; href: string; count?: string }[] = [{icon:Grid2X2,label:'Dashboard',href:'/'},{icon:BookOpen,label:'My courses',href:'/courses',count:'2'},{icon:FileCheck2,label:'Assignments',href:'/assignments',count:'3'},{icon:CalendarDays,label:'Calendar',href:'/calendar'},{icon:Sparkles,label:'Certificates',href:'/certificates'},{icon:WalletCards,label:'Payments',href:'/payments'},{icon:Settings,label:'Settings',href:'/settings'},{icon:CircleHelp,label:'Help centre',href:'/help'}]
  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark">i</div><span>inkstructs</span></div><div className="role-pill"><span className="online-dot" />Student portal<ChevronDown size={14} /></div><nav><div className="nav-label">Workspace</div>{nav.slice(0,4).map(({icon:Icon,label,href,count},i)=><a className={`nav-item ${i===0?'active':''}`} href={href} key={label}><Icon className="nav-icon" size={17}/>{label}{count && <b className={`nav-count ${label==='Assignments'?'warm':''}`}>{count}</b>}</a>)}<div className="nav-label">Your progress</div>{nav.slice(4,6).map(({icon:Icon,label,href})=><a className="nav-item" href={href} key={label}><Icon className="nav-icon" size={17}/>{label}</a>)}<div className="nav-label">Account</div>{nav.slice(6).map(({icon:Icon,label,href})=><a className="nav-item" href={href} key={label}><Icon className="nav-icon" size={17}/>{label}</a>)}</nav><div className="sidebar-footer"><div className="upgrade-card"><div className="upgrade-icon"><Flame size={18}/></div><strong>Keep learning</strong><p>You're building a great habit. 4 days in a row!</p><div className="streak">{[1,2,3,4,5,6,7].map(n=><i className={n>4?'empty':''} key={n}/>)}</div></div><div className="profile-mini"><div className="avatar">PA</div><div><strong>Paul Inya</strong><small>Student</small></div><MoreHorizontal size={17}/></div></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button><div className="crumb">My workspace <span>/</span> Dashboard</div><div className="top-actions"><button className="icon-button" onClick={()=>notify('Search is ready for your courses')}><Search size={19}/></button><button className="icon-button notify" onClick={()=>notify('You have 2 new notifications')}><Bell size={18}/><i/></button><div className="avatar small">PA</div></div></header><div className="content">
      <section className="welcome-row"><div><p className="eyebrow">MONDAY, 24 NOVEMBER 2026</p><h1>Good morning, Paul <span>✦</span></h1><p className="muted">Keep going — you're making steady progress.</p></div><button className="primary-button" onClick={()=>notify('Opening your course roadmap…')}>Continue learning <span>→</span></button></section>
      <section className="stats-grid"><Stat label="Overall progress" value="68" suffix="%" detail="Across all your courses" icon="◔" tone="purple" bar={68}/><Stat label="Learning streak" value="4" suffix=" days" detail="↑ 2 days from last week" icon={<Flame size={15}/>} tone="orange"/><Stat label="Hours learned" value="18.5" suffix=" hrs" detail="+3.2 hrs this week" icon="◷" tone="blue"/><Stat label="Certificates" value="1" detail="1 more in progress" icon="✧" tone="green"/></section>
      <div className="section-heading"><div><h2>My courses</h2><p className="muted">Your active learning paths</p></div><a href="#courses" className="view-link">View all courses <span>→</span></a></div><section className="course-grid" id="courses">{courses.map(course=><article className="course-card" key={course.title}><div className={`course-art ${course.color}-art`}><span className="art-kicker">{course.title.toUpperCase()}</span>{course.color==='ai'?<div className="art-shape">✦</div>:<div className="python-symbol">&lt;/&gt;</div>}<span className="art-code">{course.color==='ai'?<>AI<br/>LAB</>:<>01<br/>PY</>}</span></div><div className="course-body"><div className="course-meta"><span className={`tag ${course.tag}-tag`}>In progress</span><span>{course.cohort}</span></div><h3>{course.title}</h3><p className="muted">{course.description}</p><div className="course-progress"><div className={`ring ${course.color==='python'?'blue-ring':''}`} style={{'--progress':`${course.progress}%`} as React.CSSProperties}><span>{course.progress}%</span></div><div><strong>{course.week}</strong><small>{course.modules}</small></div><button className="round-arrow" onClick={()=>notify(`Opening ${course.title}…`)}>→</button></div></div></article>)}</section>
      <section className="lower-grid"><div className="panel roadmap"><div className="panel-heading"><div><h2>Continue learning</h2><p className="muted">Pick up where you left off</p></div><span className="week-badge">WEEK 5 / 8</span></div><div className="next-lesson"><div className="play-thumb"><Play size={16} fill="white"/></div><div className="lesson-copy"><span className="lesson-type">NEXT LESSON · 18 MIN</span><h3>Automating repetitive tasks with AI</h3><p className="muted">AI & Automation <span>•</span> Module 2</p><div className="tiny-progress"><i/></div></div><button className="play-button" onClick={()=>notify('Starting lesson…')}><Play size={12} fill="white"/></button></div><div className="timeline"><div className="timeline-item done"><div className="timeline-dot"><Check size={11}/></div><div><strong>Prompt engineering foundations</strong><small>Completed · 24 min</small></div></div><div className="timeline-item current"><div className="timeline-dot">→</div><div><strong>Automating repetitive tasks with AI</strong><small>Up next · 18 min</small></div></div><div className="timeline-item"><div className="timeline-dot"/><div><strong>Build your first AI workflow</strong><small>Locked until next lesson</small></div></div></div></div><div className="right-column"><div className="panel live-panel"><div className="panel-heading"><div><h2>Upcoming live class</h2><p className="muted">Don't miss your next session</p></div><span className="live-dot">LIVE</span></div><div className="session-date"><div><strong>26</strong><span>NOV</span></div><div><strong>Building useful automations</strong><small>Thursday · 6:00 PM – 7:30 PM</small></div></div><button className="secondary-button" onClick={()=>notify('Calendar reminder added')}>Add to calendar <Plus size={15}/></button></div><div className="panel announcement"><div className="panel-heading"><h2>Latest announcement</h2><MoreHorizontal size={16} className="more"/></div><div className="announcement-body"><div className="announce-icon"><Sparkles size={15}/></div><div><h3>Welcome to Week 5!</h3><p className="muted">You've reached the halfway point. Keep showing up and your future self will thank you.</p><small>Posted 2 days ago by <strong>Paul Inya</strong></small></div></div></div></div></section>
    </div></main>{toast && <div className="toast show">{toast}</div>}</div>
}
